require('dotenv').config();
const {Client,GatewayIntentBits,REST,Routes,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder}=require('discord.js');
const client=new Client({intents:[GatewayIntentBits.Guilds]});
const OWNER='1177592138968604675';
const roles=new Map(),gws=new Map(),responses=new Map();
const commands=[
{name:'setup',description:'Rollen für Commands einstellen.'},
{name:'say',description:'Eine Nachricht senden.',options:[{name:'text',description:'Text',type:3,required:true}]},
{name:'nachaus',description:'Nachricht mit bis zu 5 Optionen.',options:[{name:'nachricht',description:'Hauptnachricht',type:3,required:true},...Array.from({length:5},(_,i)=>({name:`option${i+1}`,description:`Option ${i+1}`,type:3,required:i===0})),...Array.from({length:5},(_,i)=>({name:`option${i+1}antwort`,description:`Antwort ${i+1}`,type:3,required:i===0}))]},
{name:'givewaystart',description:'Giveaway starten.',options:[{name:'preis',description:'Preis',type:3,required:true},{name:'dauer',description:'z.B. 30s, 10m, 2h, 1d',type:3,required:true},{name:'gewinner',description:'Anzahl Gewinner',type:4,required:true,min_value:1,max_value:20}]},
{name:'givewayend',description:'Giveaway vorzeitig beenden.',options:[{name:'givewayid',description:'Giveaway-ID',type:3,required:true}]},
{name:'reroll',description:'Giveaway-Gewinner neu auslosen.',options:[{name:'givewayid',description:'Giveaway-ID',type:3,required:true},{name:'anzahl',description:'Neue Gewinner',type:4,required:true,min_value:1,max_value:20}]}
];
function permitted(i){if(i.user.id===OWNER)return true;const r=roles.get(`${i.guildId}:${i.commandName}`);return !!(r&&i.member?.roles?.cache?.has(r));}
function ms(s){const m=/^(\d+)\s*(s|m|h|d)$/i.exec(s.trim());if(!m)return null;const n=+m[1],v={s:1e3,m:6e4,h:36e5,d:864e5}[m[2].toLowerCase()]*n;return v>=1e3&&v<=28*864e5?v:null;}
function gid(){return `GW-${Date.now().toString(36).toUpperCase()}-${Math.floor(1000+Math.random()*9000)}`;}
function winners(ids,n,old=[]){const a=ids.filter(x=>!old.includes(x)),r=[];while(a.length&&r.length<n)r.push(a.splice(Math.floor(Math.random()*a.length),1)[0]);return r;}
function row(id,ended=false){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gw:${id}`).setLabel(ended?'Giveaway beendet':'🎉 Beitreten').setStyle(ended?ButtonStyle.Secondary:ButtonStyle.Success).setDisabled(ended));}
async function finish(g){if(!g||g.ended)return;g.ended=true;if(g.timer)clearTimeout(g.timer);g.win=winners([...g.users],g.count);const c=await client.channels.fetch(g.channel).catch(()=>null);if(!c)return;const m=await c.messages.fetch(g.message).catch(()=>null);const w=g.win.length?g.win.map(x=>`<@${x}>`).join(', '):'Keine Teilnehmer';if(m)await m.edit({embeds:[new EmbedBuilder().setTitle('🎉 Giveaway beendet!').setDescription(`**Preis:** ${g.prize}\n\n**Gewinner:** ${w}\n\n**ID:** \`${g.id}\``).setColor('#ED4245')],components:[row(g.id,true)]}).catch(()=>{});await c.send(g.win.length?`🎉 Glückwunsch ${w}! Ihr gewinnt **${g.prize}**!`:`❌ Giveaway **${g.id}** beendet – keine Teilnehmer.`).catch(()=>{});}
async function register(){const rest=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN);await rest.put(Routes.applicationCommands(client.user.id),{body:[]});for(const guild of client.guilds.cache.values())await rest.put(Routes.applicationGuildCommands(client.user.id,guild.id),{body:commands});console.log('✅ Slash-Commands registriert.');}
client.once('ready',async()=>{console.log(`🤖 Online: ${client.user.tag}`);try{await register()}catch(e){console.error('❌ Registrierung fehlgeschlagen:',e)}});
client.on('guildCreate',async g=>{try{const r=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN);await r.put(Routes.applicationGuildCommands(client.user.id,g.id),{body:commands})}catch(e){console.error(e)}});
client.on('interactionCreate',async i=>{try{
if(i.isButton()&&i.customId.startsWith('gw:')){const g=gws.get(i.customId.slice(3));if(!g||g.ended)return i.reply({content:'❌ Dieses Giveaway ist beendet.',ephemeral:true});if(g.users.has(i.user.id)){g.users.delete(i.user.id);return i.reply({content:'🚪 Du hast das Giveaway verlassen.',ephemeral:true})}g.users.add(i.user.id);return i.reply({content:'🎉 Du bist dabei! Erneut drücken zum Verlassen.',ephemeral:true})}
if(i.isStringSelectMenu()){if(i.customId==='setup:cmd'){if(i.user.id!==OWNER)return i.reply({content:'❌ Nur der Owner.',ephemeral:true});const rs=i.guild.roles.cache.filter(r=>r.id!==i.guild.id&&!r.managed).sort((a,b)=>b.position-a.position).first(25);const menu=new StringSelectMenuBuilder().setCustomId(`setup:role:${i.values[0]}`).setPlaceholder('Rolle auswählen...').addOptions(rs.map(r=>({label:r.name.slice(0,100),value:r.id})));return i.update({content:`Rolle für **/${i.values[0]}** auswählen:`,embeds:[],components:[new ActionRowBuilder().addComponents(menu)]})}if(i.customId.startsWith('setup:role:')){const cmd=i.customId.split(':')[2];roles.set(`${i.guildId}:${cmd}`,i.values[0]);return i.update({content:`✅ **/${cmd}**: <@&${i.values[0]}>`,embeds:[],components:[]})}if(i.customId.startsWith('na:')){const x=responses.get(i.customId)?.find(x=>x.v===i.values[0]);return i.reply({content:x?.a||'❌ Antwort nicht gefunden.',ephemeral:true})}}
if(!i.isChatInputCommand())return;
if(i.commandName==='setup'){if(i.user.id!==OWNER)return i.reply({content:'❌ Nur der Owner darf /setup benutzen.',ephemeral:true});const menu=new StringSelectMenuBuilder().setCustomId('setup:cmd').setPlaceholder('Command auswählen...').addOptions(commands.filter(c=>c.name!=='setup').map(c=>({label:`/${c.name}`,value:c.name})));return i.reply({embeds:[new EmbedBuilder().setTitle('⚙️ Setup').setDescription('Wähle einen Command und danach die Rolle.').setColor('#5865F2')],components:[new ActionRowBuilder().addComponents(menu)],ephemeral:true})}
if(!permitted(i))return i.reply({content:'❌ Keine Berechtigung.',ephemeral:true});
if(i.commandName==='say'){await i.channel.send(i.options.getString('text',true));return i.reply({content:'✅ Gesendet.',ephemeral:true})}
if(i.commandName==='nachaus'){const a=[];for(let n=1;n<=5;n++){const o=i.options.getString(`option${n}`),ans=i.options.getString(`option${n}antwort`);if(o&&ans)a.push({v:String(n),label:o,a:ans})}if(!a.length)return i.reply({content:'❌ Mindestens eine Option benötigt.',ephemeral:true});const id=`na:${Date.now()}:${i.user.id}`;responses.set(id,a);const menu=new StringSelectMenuBuilder().setCustomId(id).setPlaceholder('Option auswählen...').addOptions(a.map(x=>({label:x.label.slice(0,100),value:x.v})));await i.channel.send({embeds:[new EmbedBuilder().setDescription(i.options.getString('nachricht',true)).setColor('#5865F2')],components:[new ActionRowBuilder().addComponents(menu)]});return i.reply({content:'✅ Gesendet.',ephemeral:true})}
if(i.commandName==='givewaystart'){const time=ms(i.options.getString('dauer',true));if(!time)return i.reply({content:'❌ Dauer ungültig. Beispiel: 30s, 10m, 2h, 1d.',ephemeral:true});const g={id:gid(),channel:i.channelId,message:null,creator:i.user.id,prize:i.options.getString('preis',true),count:i.options.getInteger('gewinner',true),users:new Set(),win:[],ended:false};const until=Date.now()+time;const m=await i.channel.send({embeds:[new EmbedBuilder().setTitle('🎉 GIVEAWAY').setDescription(`**🎁 Preis:** ${g.prize}\n\n**🏆 Gewinner:** ${g.count}\n\n**⏱️ Ende:** <t:${Math.floor(until/1000)}:R>\n\nKlicke auf **🎉 Beitreten**!\n\n**🆔 ID:** \`${g.id}\``).setColor('#57F287')],components:[row(g.id)]});g.message=m.id;gws.set(g.id,g);g.timer=setTimeout(()=>finish(g),time);return i.reply({content:`✅ Giveaway erstellt! ID: **${g.id}**`,ephemeral:true})}
if(i.commandName==='givewayend'){const g=gws.get(i.options.getString('givewayid',true));if(!g)return i.reply({content:'❌ ID nicht gefunden.',ephemeral:true});if(g.creator!==i.user.id&&i.user.id!==OWNER)return i.reply({content:'❌ Nur Ersteller oder Owner.',ephemeral:true});await finish(g);return i.reply({content:'✅ Beendet.',ephemeral:true})}
if(i.commandName==='reroll'){const g=gws.get(i.options.getString('givewayid',true)),n=i.options.getInteger('anzahl',true);if(!g)return i.reply({content:'❌ ID nicht gefunden.',ephemeral:true});if(!g.ended)return i.reply({content:'❌ Noch nicht beendet.',ephemeral:true});const w=winners([...g.users],n,g.win);if(!w.length)return i.reply({content:'❌ Keine weiteren Teilnehmer.',ephemeral:true});g.win.push(...w);await i.channel.send(`🔄 **Reroll**\n🏆 ${w.map(x=>`<@${x}>`).join(', ')}\n🎁 **${g.prize}**`);return i.reply({content:'✅ Reroll durchgeführt.',ephemeral:true})}
}catch(e){console.error('Interaction:',e);if(!i.replied&&!i.deferred)await i.reply({content:'❌ Fehler im Bot.',ephemeral:true}).catch(()=>{})}});
client.login(process.env.DISCORD_TOKEN);