require('dotenv').config();
const { Client, GatewayIntentBits, REST, Routes, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, StringSelectMenuBuilder } = require('discord.js');
const OWNER_ID='1177592138968604675';
const client=new Client({intents:[GatewayIntentBits.Guilds]});
const roles=new Map(), giveaways=new Map(), nachaus=new Map();
const commands=[
{name:'setup',description:'Berechtigungen einstellen.'},
{name:'say',description:'Der Bot sendet eine Nachricht.',options:[{name:'text',description:'Nachricht',type:3,required:true}]},
{name:'nachaus',description:'Nachricht mit bis zu 5 Auswahlmöglichkeiten.',options:[{name:'nachricht',description:'Hauptnachricht',type:3,required:true},{name:'option1',description:'Option 1',type:3,required:true},{name:'option1antwort',description:'Antwort 1',type:3,required:true},{name:'option2',description:'Option 2',type:3,required:false},{name:'option2antwort',description:'Antwort 2',type:3,required:false},{name:'option3',description:'Option 3',type:3,required:false},{name:'option3antwort',description:'Antwort 3',type:3,required:false},{name:'option4',description:'Option 4',type:3,required:false},{name:'option4antwort',description:'Antwort 4',type:3,required:false},{name:'option5',description:'Option 5',type:3,required:false},{name:'option5antwort',description:'Antwort 5',type:3,required:false}]},
{name:'givewaystart',description:'Giveaway starten.',options:[{name:'preis',description:'Preis',type:3,required:true},{name:'dauer',description:'z.B. 30s, 10m, 2h, 1d',type:3,required:true},{name:'gewinner',description:'Anzahl Gewinner',type:4,required:true,min_value:1,max_value:20}]},
{name:'givewayend',description:'Giveaway beenden.',options:[{name:'givewayid',description:'Giveaway-ID',type:3,required:true}]},
{name:'reroll',description:'Gewinner neu auslosen.',options:[{name:'givewayid',description:'Giveaway-ID',type:3,required:true},{name:'anzahl',description:'Anzahl',type:4,required:true,min_value:1,max_value:20}]}
];
function allowed(i){if(i.user.id===OWNER_ID)return true;const r=roles.get(`${i.guildId}:${i.commandName}`);return !!(r&&i.member?.roles?.cache?.has(r));}
function parseDuration(v){const m=/^(\d+)\s*(s|m|h|d)$/i.exec(v.trim());if(!m)return null;const x=Number(m[1])*({s:1000,m:60000,h:3600000,d:86400000}[m[2].toLowerCase()]);return x>=1000&&x<=28*86400000?x:null;}
function newId(){return `GW-${Date.now().toString(36).toUpperCase()}-${Math.floor(1000+Math.random()*9000)}`;}
function pick(ids,n,exclude=[]){const a=ids.filter(x=>!exclude.includes(x)),r=[];while(a.length&&r.length<n)r.push(a.splice(Math.floor(Math.random()*a.length),1)[0]);return r;}
function gwRow(id,end=false){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gw:${id}`).setLabel(end?'Giveaway beendet':'🎉 Beitreten').setStyle(end?ButtonStyle.Secondary:ButtonStyle.Success).setDisabled(end));}
async function finish(g){if(!g||g.ended)return;g.ended=true;if(g.timer)clearTimeout(g.timer);g.winners=pick([...g.entries],g.winnerCount);const c=await client.channels.fetch(g.channelId).catch(()=>null);if(!c)return;const m=await c.messages.fetch(g.messageId).catch(()=>null);const w=g.winners.length?g.winners.map(x=>`<@${x}>`).join(', '):'Keine Teilnehmer';if(m)await m.edit({embeds:[new EmbedBuilder().setTitle('🎉 Giveaway beendet!').setDescription(`**Preis:** ${g.prize}\n\n**Gewinner:** ${w}\n\n**Giveaway-ID:** \`${g.id}\``).setColor('#ED4245')],components:[gwRow(g.id,true)]}).catch(()=>{});await c.send(g.winners.length?`🎉 Glückwunsch ${w}! Ihr habt **${g.prize}** gewonnen!\n🆔 ${g.id}`:`❌ Giveaway **${g.id}** beendet – keine Teilnehmer.`).catch(()=>{});}
async function register(){const r=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN);await r.put(Routes.applicationCommands(client.user.id),{body:[]});for(const g of client.guilds.cache.values())await r.put(Routes.applicationGuildCommands(client.user.id,g.id),{body:commands});}
client.once('ready',async()=>{console.log(`Bot online: ${client.user.tag}`);try{await register();console.log('Commands registriert.');}catch(e){console.error(e);}});
client.on('guildCreate',async g=>{try{const r=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN);await r.put(Routes.applicationGuildCommands(client.user.id,g.id),{body:commands});}catch(e){console.error(e);}});
client.on('interactionCreate',async i=>{try{
if(i.isButton()&&i.customId.startsWith('gw:')){const g=giveaways.get(i.customId.slice(3));if(!g||g.ended)return i.reply({content:'❌ Dieses Giveaway ist beendet.',ephemeral:true});if(g.entries.has(i.user.id)){g.entries.delete(i.user.id);return i.reply({content:'🚪 Du hast das Giveaway verlassen.',ephemeral:true});}g.entries.add(i.user.id);return i.reply({content:'🎉 Du bist dabei! Drücke erneut zum Verlassen.',ephemeral:true});}
if(i.isStringSelectMenu()){if(i.customId==='setup:command'){if(i.user.id!==OWNER_ID)return i.reply({content:'❌ Nur der Owner.',ephemeral:true});const n=i.values[0],rs=i.guild.roles.cache.filter(r=>r.id!==i.guild.id&&!r.managed).sort((a,b)=>b.position-a.position).first(25);if(!rs.length)return i.reply({content:'❌ Keine Rollen gefunden.',ephemeral:true});const menu=new StringSelectMenuBuilder().setCustomId(`setup:role:${n}`).setPlaceholder('Rolle auswählen...').addOptions(rs.map(r=>({label:r.name.slice(0,100),value:r.id})));return i.update({content:`⚙️ Rolle für **/${n}** auswählen:`,embeds:[],components:[new ActionRowBuilder().addComponents(menu)]});}if(i.customId.startsWith('setup:role:')){if(i.user.id!==OWNER_ID)return i.reply({content:'❌ Kein Zugriff.',ephemeral:true});const n=i.customId.split(':')[2],r=i.values[0];roles.set(`${i.guildId}:${n}`,r);return i.update({content:`✅ **/${n}** kann jetzt von <@&${r}> benutzt werden.`,embeds:[],components:[]});}if(i.customId.startsWith('na:')){const d=nacha us.get(i.customId);const x=d?.find(x=>x.value===i.values[0]);return i.reply({content:x?.answer||'❌ Antwort nicht gefunden.',ephemeral:true});}}
if(!i.isChatInputCommand())return;
if(i.commandName==='setup'){if(i.user.id!==OWNER_ID)return i.reply({content:'❌ Nur der Owner darf /setup benutzen.',ephemeral:true});const menu=new StringSelectMenuBuilder().setCustomId('setup:command').setPlaceholder('Command auswählen...').addOptions(commands.filter(c=>c.name!=='setup').map(c=>({label:`/${c.name}`,value:c.name,description:c.description.slice(0,100)})));return i.reply({embeds:[new EmbedBuilder().setTitle('⚙️ Bot Setup').setDescription('Command auswählen und Rolle festlegen.').setColor('#5865F2')],components:[new ActionRowBuilder().addComponents(menu)],ephemeral:true});}
if(!allowed(i))return i.reply({content:'❌ Du hast keine Berechtigung.',ephemeral:true});
if(i.commandName==='say'){await i.channel.send(i.options.getString('text',true));return i.reply({content:'✅ Gesendet.',ephemeral:true});}
if(i.commandName==='nachaus'){const list=[];for(let n=1;n<=5;n++){const o=i.options.getString(`option${n}`),a=i.options.getString(`option${n}antwort`);if(o&&a)list.push({value:String(n),label:o,answer:a});}if(!list.length)return i.reply({content:'❌ Mindestens eine Option benötigt.',ephemeral:true});const id=`na:${i.user.id}:${Date.now()}`;nacha us.set(id,list);const menu=new StringSelectMenuBuilder().setCustomId(id).setPlaceholder('Option auswählen...').addOptions(list.map(x=>({label:x.label.slice(0,100),value:x.value})));await i.channel.send({embeds:[new EmbedBuilder().setDescription(i.options.getString('nachricht',true)).setColor('#5865F2')],components:[new ActionRowBuilder().addComponents(menu)]});return i.reply({content:'✅ Gesendet.',ephemeral:true});}
if(i.commandName==='givewaystart'){const ms=parseDuration(i.options.getString('dauer',true));if(!ms)return i.reply({content:'❌ Ungültige Dauer. Nutze z.B. 30s, 10m, 2h oder 1d.',ephemeral:true});const g={id:newId(),channelId:i.channelId,messageId:null,creator:i.user.id,prize:i.options.getString('preis',true),winnerCount:i.options.getInteger('gewinner',true),entries:new Set(),winners:[],ended:false,timer:null};const end=Date.now()+ms;const e=new EmbedBuilder().setTitle('🎉 GIVEAWAY').setDescription(`**🎁 Preis:** ${g.prize}\n\n**🏆 Gewinner:** ${g.winnerCount}\n\n**⏱️ Endet:** <t:${Math.floor(end/1000)}:R>\n\nKlicke auf **🎉 Beitreten**!\n\n**🆔 Giveaway-ID:** \`${g.id}\``).setColor('#57F287');const m=await i.channel.send({embeds:[e],components:[gwRow(g.id)]});g.messageId=m.id;giveaways.set(g.id,g);g.timer=setTimeout(()=>finish(g),ms);return i.reply({content:`✅ Giveaway erstellt!\n🆔 **${g.id}**`,ephemeral:true});}
if(i.commandName==='givewayend'){const g=giveaways.get(i.options.getString('givewayid',true));if(!g)return i.reply({content:'❌ Giveaway-ID nicht gefunden.',ephemeral:true});if(g.creator!==i.user.id&&i.user.id!==OWNER_ID)return i.reply({content:'❌ Nur Ersteller oder Owner.',ephemeral:true});if(g.ended)return i.reply({content:'❌ Bereits beendet.',ephemeral:true});await finish(g);return i.reply({content:'✅ Giveaway beendet.',ephemeral:true});}
if(i.commandName==='reroll'){const id=i.options.getString('givewayid',true),n=i.options.getInteger('anzahl',true),g=giveaways.get(id);if(!g)return i.reply({content:'❌ Giveaway-ID nicht gefunden.',ephemeral:true});if(!g.ended)return i.reply({content:'❌ Noch nicht beendet.',ephemeral:true});const w=pick([...g.entries],n,g.winners);if(!w.length)return i.reply({content:'❌ Keine weiteren Teilnehmer.',ephemeral:true});g.winners.push(...w);await i.channel.send(`🔄 **Reroll** für \`${id}\`\n🏆 Neue Gewinner: ${w.map(x=>`<@${x}>`).join(', ')}\n🎁 Preis: **${g.prize}**`);return i.reply({content:'✅ Reroll durchgeführt.',ephemeral:true});}
}catch(e){console.error(e);if(!i.replied&&!i.deferred)await i.reply({content:'❌ Es ist ein Fehler aufgetreten.',ephemeral:true}).catch(()=>{});}});
client.login(process.env.DISCORD_TOKEN);